spring.application.name=certvalidator
# You must set this env var befor runing the app or replce them with default ones with ":"
keys.default.cacerts.password=${APP_DEFAULT_CA_CERT_PASSWORD:ubfaihuerbfh}
cert.path.validation.algorithm=${APP_CERT_VALIDATION_ALGO:PKIX}
keys.default.keymanager.password=${APP_KEYMANAGER_PW:uerifhneilruf}
keys.default.keymanager.container.format=${APP_KEYMANAGER_KEYSTORE_FORMAT:PKCS12}
cert.san.allow=${APP_CERT_SAN_ALLOW}